name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Static SDK
    runs-on: ubuntu-latest
    container: swift:latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Static SDK
        run: |
          swift sdk install https://download.swift.org/swift-6.2.3-release/static-sdk/swift-6.2.3-RELEASE/swift-6.2.3-RELEASE_static-linux-0.0.1.artifactbundle.tar.gz --checksum f30ec724d824ef43b5546e02ca06a8682dafab4b26a99fbb0e858c347e507a2c
      - name: Build x86_64
        run: swift build --swift-sdk x86_64-swift-linux-musl -c release
      - name: Build aarch64
        run: swift build --swift-sdk aarch64-swift-linux-musl -c release
